### PR TITLE
General: Use std::array where applicable

### PR DESCRIPTION
**Pull request by lioncash**
Amends #7 by resolving issues with it on GCC due to use of a pre-existing compiler extension.

Would recommend compilation testing by someone with GCC on hand.

---
This change is [Reviewable](https://reviewable.io/reviews/axiodl/kabufuda/10)

### CODE REVIEW

**Comment by Antidote** [comment]
No dice, same issue
```
../kabufuda/include/kabufuda/Directory.hpp:12:12: error: ‘struct kabufuda::Directory::<unnamed union>::Data’ invalid; an anonymous union may only have public non-static data members [-fpermissive]
   12 |     struct Data {
      |            ^~~~
```

**Comment by Antidote** [comment]
AH-HA!
Moving the definitions outside the anon unions fixes up the compile errors.

This includes `using FlashID = std::array<std::array<uint8_t, 12>, 2>;` in SRAM.hpp

**Comment by lioncash** [comment]
Amended the code

**Comment by Antidote** [comment]
Alright! it compiles with the amended code.

**Pull request merged**
